"""add cascading deletes

Revision ID: 0eb76f19ff5a
Revises: a1a9c7e0088c
Create Date: 2026-08-25 20:29:05.735851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb76f19ff5a'
down_revision = 'a1a9c7e0088c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('courses_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('enrollments_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('enrollments_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lesson_completions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_completions_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lesson_completions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lessons_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('materials_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('materials_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('modules_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('progress_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('progress_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('questions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('quiz_results_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('quiz_results_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('quizzes_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('quizzes_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quizzes_ibfk_2'), 'users', ['instructor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('quizzes_ibfk_1'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quiz_results_ibfk_1'), 'quizzes', ['quiz_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('quiz_results_ibfk_2'), 'users', ['student_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questions_ibfk_1'), 'quizzes', ['quiz_id'], ['id'])

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('progress_ibfk_1'), 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('progress_ibfk_2'), 'users', ['student_id'], ['id'])

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('modules_ibfk_1'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('materials_ibfk_1'), 'modules', ['module_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('materials_ibfk_2'), 'users', ['uploaded_by'], ['id'])

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lessons_ibfk_1'), 'modules', ['module_id'], ['id'])

    with op.batch_alter_table('lesson_completions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_completions_ibfk_1'), 'lessons', ['lesson_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('lesson_completions_ibfk_2'), 'users', ['student_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('enrollments_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('enrollments_ibfk_1'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('courses_ibfk_1'), 'users', ['instructor_id'], ['id'])

    # ### end Alembic commands ###
