"""Add OTP fields to User model

Revision ID: a1a9c7e0088c
Revises: f60bf5b0fe0a
Create Date: 2026-08-24 19:31:48.582821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a9c7e0088c'
down_revision = 'f60bf5b0fe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_hash')

    # ### end Alembic commands ###
