pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
        DOCKER_HOST        = 'tcp://localhost:2375'
        FLASK_ENV          = 'testing'
        SECRET_KEY         = 'jenkins-test-secret-key'
        JWT_SECRET_KEY     = 'jenkins-test-jwt-secret-key'
        TEST_DATABASE_URI  = 'sqlite:///test.db'
        EMAIL              = 'sunitagawas580@gmail.com'
        APP_PASSWORD       = 'thbpduiejsshwuqi'

        PYTHON_PATH = 'C:\\Users\\hp\\AppData\\Local\\Python\\pythoncore-3.14-64\\python.exe'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies & Test') {
            steps {
                bat """
                    "${env.PYTHON_PATH}" --version
                    "${env.PYTHON_PATH}" -m pip install -r Devops-proj\\requirements.txt
                    cd Devops-proj
                    "${env.PYTHON_PATH}" -m pytest -v
                """
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Devops-proj') {
                    bat 'docker build -t tanmaigawas/flask-app:latest .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat '''
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                        docker push tanmaigawas/flask-app:latest
                        docker logout
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
            emailext(
                subject: "SUCCESS ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <h2>Jenkins build Successful</h2>
                    <p><b>URL</b>: ${env.BUILD_URL}</p>
                """,
                to: "gawastanmay373@gmail.com"
            )
        }

        failure {
            echo 'Pipeline failed!'
            emailext(
                subject: "FAILED ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <h2>Jenkins build Failed</h2>
                    <p><b>URL</b>: ${env.BUILD_URL}</p>
                """,
                to: "gawastanmay373@gmail.com"
            )
        }
    }
}