pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
    steps {
        dir('Devops-proj') {
            bat '''
                where python
                python --version
                where py
                py --version
                py -m pip --version
                py -m pip install -r requirements.txt
            '''
        }
    }
}

        stage('Test') {
            steps {
                dir('Devops-proj') {
                    bat 'pytest'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Devops-proj') {
                    bat 'docker build -t tanmaigawas/flask-app:latest .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat '''
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                        docker push tanmaigawas/flask-app:latest
                        docker logout
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}