pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
    steps {
        bat '"C:\\Users\\hp\\AppData\\Local\\Python\\pythoncore-3.14-64\\python.exe" -m pip install -r Devops-proj\\requirements.txt'
    }
}

        stage('Test') {
    steps {
        bat '''
        cd Devops-proj
        set FLASK_ENV=testing
        "C:\\Users\\hp\\AppData\\Local\\Python\\pythoncore-3.14-64\\python.exe" -m pytest
        '''
    }
}

        stage('Build Docker Image') {
            steps {
                dir('Devops-proj') {
                    bat 'docker build -t tanmaigawas/flask-app:latest .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    bat '''
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                        docker push tanmaigawas/flask-app:latest
                        docker logout
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}